name: UI Automation Test

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Give execute permission
        run: chmod +x gradlew

      - name: Run UI Automation Test
        run: ./gradlew test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Report
          path: build/reports/